version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Scripts/start_server.sh
      timeout: 300
      runas: root
